import { useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import type { ChangeEvent, FormEvent } from 'react'

import { InfoCard } from '../../components/ui/InfoCard'
import { ApiError } from '../../lib/api'
import { useSession } from '../auth/useSession'
import { useItemsByCategories } from '../items/api'
import { useOfficialTemplates } from '../templates/api'
import {
  BASELINE_DEFAULT_ITEMS,
  BASELINE_OPTIONS,
  STANDARD_ITEM_OPTIONS,
  STRUCTURE_OPTIONS,
  type StandardItemKey,
  type StructureType,
  findBaselineById,
} from './createTakeoffConfig'
import { useCreateProject, useGenerateTakeoff, useProjects } from './api'

type ProjectMode = 'existing' | 'create'

type PlanFormState = {
  stories: string
  kitchens: string
  garbage_disposals: string
  laundry_rooms: string
  lav_faucets: string
  toilets: string
  showers: string
  bathtubs: string
  half_baths: string
  double_bowl_vanities: string
  hose_bibbs: string
  ice_makers: string
  water_heater_tank_qty: string
  water_heater_tankless_qty: string
  sewer_distance_lf: string
  water_distance_lf: string
}

type StandardItemSelections = Record<StandardItemKey, string>

type ExtraItemDraft = {
  id: string
  item_label: string
  stage: 'ground' | 'topout' | 'final'
}

type DraftItemModal = {
  label: string
  code: string
  category: StandardItemKey | ''
}

type AutoGeneratedLine = {
  code: string
  label: string
  qty: string
  stage: 'ground' | 'topout' | 'final'
  factor: string
}

const INITIAL_PLAN: PlanFormState = {
  stories: '2',
  kitchens: '1',
  garbage_disposals: '1',
  laundry_rooms: '1',
  lav_faucets: '3',
  toilets: '3',
  showers: '1',
  bathtubs: '1',
  half_baths: '0',
  double_bowl_vanities: '0',
  hose_bibbs: '2',
  ice_makers: '0',
  water_heater_tank_qty: '0',
  water_heater_tankless_qty: '1',
  sewer_distance_lf: '25',
  water_distance_lf: '25',
}

const STORY_FAMILIES = {
  '1': {
    groundMaterial: 'FW50M90010',
    groundLabor: 'FW50L90010',
    topoutMaterial: 'FW50M90020',
    topoutLabor: 'FW50L90020',
    finalMaterial: 'FW50M90030',
    finalLabor: 'FW50L90030',
  },
  '2': {
    groundMaterial: 'FW50M90110',
    groundLabor: 'FW50L90110',
    topoutMaterial: 'FW50M90120',
    topoutLabor: 'FW50L90120',
    finalMaterial: 'FW50M90130',
    finalLabor: 'FW50L90130',
  },
  '3': {
    groundMaterial: 'FW50M90140',
    groundLabor: 'FW50L90140',
    topoutMaterial: 'FW50M90150',
    topoutLabor: 'FW50L90150',
    finalMaterial: 'FW50M90160',
    finalLabor: 'FW50L90160',
  },
  '4': {
    groundMaterial: '4W50M90110',
    groundLabor: '4W50L90110',
    topoutMaterial: '4W50M90120',
    topoutLabor: '4W50L90120',
    finalMaterial: '4W50M90130',
    finalLabor: '4W50L90130',
  },
} as const

const STANDARD_ROWS: Array<{
  key: StandardItemKey
  label: string
  quantityKey:
    | 'kitchens'
    | 'garbage_disposals'
    | 'lav_faucets'
    | 'toilets'
    | 'showers'
    | 'bathtubs'
    | 'half_baths'
    | 'hose_bibbs'
    | 'ice_makers'
    | 'water_heater_tank_qty'
    | 'water_heater_tankless_qty'
  helpText?: string
  category: string
}> = [
  { key: 'kitchenFaucet', label: 'Kitchen Faucet', quantityKey: 'kitchens', category: 'Kitchen Faucet' },
  { key: 'garbageDisposal', label: 'Garbage Disposal', quantityKey: 'garbage_disposals', category: 'Garbage Disposal' },
  { key: 'lavFaucet', label: 'Lav Faucet', quantityKey: 'lav_faucets', category: 'Lav Faucet' },
  { key: 'toilet', label: 'Toilets', quantityKey: 'toilets', category: 'Toilet' },
  { key: 'showerTrim', label: 'Shower Trim', quantityKey: 'showers', category: 'Shower Trim' },
  { key: 'tubShowerTrim', label: 'Tub & Shower Trim', quantityKey: 'bathtubs', category: 'Tub Shower Trim' },
  { key: 'bathTub', label: 'BathTub', quantityKey: 'bathtubs', category: 'Bathtub' },
  {
    key: 'pedestal',
    label: 'Pedestal',
    quantityKey: 'half_baths',
    category: 'Pedestal',
    helpText: 'Pedestal replaces the old half-bath concept in the UI.',
  },
  { key: 'hoseBibb', label: 'Hose Bibbs', quantityKey: 'hose_bibbs', category: 'Hose Bibb' },
  {
    key: 'iceMaker',
    label: 'Ice Makers',
    quantityKey: 'ice_makers',
    category: 'Ice Maker',
    helpText: 'Current official baselines still drive the primary kitchen connection from Kitchens.',
  },
  { key: 'tankWaterHeater', label: 'Tank Water Heater', quantityKey: 'water_heater_tank_qty', category: 'Install Water Heater' },
  {
    key: 'tanklessWaterHeater',
    label: 'Tankless Water Heater',
    quantityKey: 'water_heater_tankless_qty',
    category: 'Tankless Water Heater',
  },
]

function generateProjectCode(projectName: string) {
  const stem = projectName
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '')
    .slice(0, 6) || 'PRJ'
  const random = crypto.randomUUID().split('-')[0].toUpperCase()
  return `${stem}-${random}`
}

function toNumber(value: string) {
  const parsed = Number(value)
  return Number.isFinite(parsed) ? parsed : 0
}

function numberString(value: number) {
  return Number.isInteger(value) ? String(value) : value.toFixed(1)
}

function buildInitialSelections(templateCode: keyof typeof BASELINE_DEFAULT_ITEMS | null): StandardItemSelections {
  const fallback = Object.fromEntries(
    Object.entries(STANDARD_ITEM_OPTIONS).map(([key, options]) => [key, options[0]?.code ?? '']),
  ) as StandardItemSelections

  if (!templateCode) {
    return fallback
  }

  return {
    ...fallback,
    ...BASELINE_DEFAULT_ITEMS[templateCode],
  }
}

function NumberField({
  label,
  min = 0,
  name,
  onChange,
  step = '1',
  value,
}: {
  label: string
  min?: number
  name: keyof PlanFormState
  onChange: (event: ChangeEvent<HTMLInputElement>) => void
  step?: string
  value: string
}) {
  return (
    <label className="block">
      <span className="mb-2 block text-sm font-medium text-slate-700">{label}</span>
      <input
        className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
        min={min}
        name={name}
        onChange={onChange}
        required
        step={step}
        type="number"
        value={value}
      />
    </label>
  )
}

export function NewTakeoffPage() {
  const session = useSession()
  const projects = useProjects()
  const templates = useOfficialTemplates()
  const categoryItems = useItemsByCategories(STANDARD_ROWS.map((row) => row.category))
  const createProject = useCreateProject()
  const generateTakeoff = useGenerateTakeoff()

  const [projectMode, setProjectMode] = useState<ProjectMode>('existing')
  const [selectedProjectCode, setSelectedProjectCode] = useState('')
  const [projectName, setProjectName] = useState('')
  const [contractorName, setContractorName] = useState('Lennar')
  const [foremanName, setForemanName] = useState('')
  const [structureType, setStructureType] = useState<StructureType>('TH')
  const [baselineId, setBaselineId] = useState<string>('th-standard')
  const [modelsInput, setModelsInput] = useState('')
  const [models, setModels] = useState<string[]>([])
  const [plan, setPlan] = useState<PlanFormState>(INITIAL_PLAN)
  const [waterPointsOverride, setWaterPointsOverride] = useState('')
  const [hasPreviewed, setHasPreviewed] = useState(false)
  const [showExtras, setShowExtras] = useState(false)
  const [extraItems, setExtraItems] = useState<ExtraItemDraft[]>([])
  const [showCreateItemModal, setShowCreateItemModal] = useState(false)
  const [draftItemModal, setDraftItemModal] = useState<DraftItemModal>({
    label: '',
    code: '',
    category: '',
  })
  const [catalogDrafts, setCatalogDrafts] = useState<Record<StandardItemKey, Array<{ code: string; label: string }>>>(
    STANDARD_ITEM_OPTIONS,
  )
  const [itemOverrides, setItemOverrides] = useState<Partial<StandardItemSelections>>({})
  const [existingTakeoffConflict, setExistingTakeoffConflict] = useState<{
    project_code: string
    template_code: string
    takeoff_id: string
  } | null>(null)

  const isBusy = createProject.isPending || generateTakeoff.isPending

  const activeProjects = useMemo(
    () => (projects.data ?? []).filter((project) => project.status === 'open'),
    [projects.data],
  )

  const availableBaselines = useMemo(() => {
    const officialTemplateCodes = new Set((templates.data ?? []).map((template) => template.template_code))
    return BASELINE_OPTIONS.filter(
      (option) => option.structureType === structureType && officialTemplateCodes.has(option.templateCode),
    )
  }, [structureType, templates.data])

  const selectedProject = useMemo(
    () => activeProjects.find((project) => project.project_code === selectedProjectCode) ?? null,
    [activeProjects, selectedProjectCode],
  )

  const effectiveBaselineId =
    structureType === 'Custom'
      ? ''
      : availableBaselines.some((option) => option.id === baselineId)
        ? baselineId
        : (availableBaselines[0]?.id ?? '')

  const effectiveBaseline = useMemo(
    () => findBaselineById(effectiveBaselineId),
    [effectiveBaselineId],
  )

  const itemSelections = useMemo(
    () => ({
      ...buildInitialSelections(effectiveBaseline?.templateCode ?? null),
      ...itemOverrides,
    }),
    [effectiveBaseline?.templateCode, itemOverrides],
  )

  const derivedWaterPoints = useMemo(() => {
    return (
      toNumber(plan.kitchens) +
      toNumber(plan.laundry_rooms) +
      toNumber(plan.lav_faucets) +
      toNumber(plan.toilets) +
      toNumber(plan.showers) +
      toNumber(plan.bathtubs) -
      toNumber(plan.double_bowl_vanities) * 2
    )
  }, [plan])

  const effectiveWaterPoints = waterPointsOverride.trim() === '' ? derivedWaterPoints : Number(waterPointsOverride)

  const autoGeneratedLines = useMemo<AutoGeneratedLine[]>(() => {
    const storyKey = (plan.stories in STORY_FAMILIES ? plan.stories : '2') as keyof typeof STORY_FAMILIES
    const storyFamily = STORY_FAMILIES[storyKey]
    const lines: AutoGeneratedLine[] = [
      {
        code: storyFamily.groundMaterial,
        label: "MAT'L PER FIXTURE",
        qty: numberString(effectiveWaterPoints),
        stage: 'ground',
        factor: '0.30',
      },
      {
        code: storyFamily.groundLabor,
        label: 'LABOR PER FIXTURE',
        qty: numberString(effectiveWaterPoints),
        stage: 'ground',
        factor: '0.30',
      },
      {
        code: storyFamily.topoutMaterial,
        label: "MAT'L PER FIXTURE",
        qty: numberString(effectiveWaterPoints),
        stage: 'topout',
        factor: '0.30',
      },
      {
        code: storyFamily.topoutLabor,
        label: 'LABOR PER FIXTURE',
        qty: numberString(effectiveWaterPoints),
        stage: 'topout',
        factor: '0.30',
      },
      {
        code: storyFamily.finalMaterial,
        label: "MAT'L PER FIXTURE",
        qty: numberString(effectiveWaterPoints),
        stage: 'final',
        factor: '0.40',
      },
      {
        code: storyFamily.finalLabor,
        label: 'LABOR PER FIXTURE',
        qty: numberString(effectiveWaterPoints),
        stage: 'final',
        factor: '0.40',
      },
      {
        code: 'FW50M91110',
        label: 'MATERIAL FOR SEWER WASTE PIPE',
        qty: plan.sewer_distance_lf || '0',
        stage: 'ground',
        factor: '1.00',
      },
      {
        code: 'FW50L91110',
        label: 'LABOR FOR SEWER WASTE PIPE',
        qty: plan.sewer_distance_lf || '0',
        stage: 'ground',
        factor: '1.00',
      },
      {
        code: 'FW50M91210',
        label: 'MATERIAL FOR WATER SUPPLY LINE',
        qty: plan.water_distance_lf || '0',
        stage: 'ground',
        factor: '1.00',
      },
      {
        code: 'FW50L91210',
        label: 'LABOR FOR WATER SUPPLY LINE',
        qty: plan.water_distance_lf || '0',
        stage: 'ground',
        factor: '1.00',
      },
    ]

    if (toNumber(plan.double_bowl_vanities) > 0) {
      const qty = plan.double_bowl_vanities
      lines.push(
        {
          code: 'FW50M90210',
          label: 'DBL-BOWL MATERIAL',
          qty,
          stage: 'ground',
          factor: '0.30',
        },
        {
          code: 'FW50L90210',
          label: 'DBL-BOWL LABOR',
          qty,
          stage: 'ground',
          factor: '0.30',
        },
        {
          code: 'FW50M90220',
          label: 'DBL-BOWL MATERIAL',
          qty,
          stage: 'topout',
          factor: '0.30',
        },
        {
          code: 'FW50L90220',
          label: 'DBL-BOWL LABOR',
          qty,
          stage: 'topout',
          factor: '0.30',
        },
        {
          code: 'FW50M90230',
          label: 'DBL-BOWL MATERIAL',
          qty,
          stage: 'final',
          factor: '0.40',
        },
        {
          code: 'FW50L90230',
          label: 'DBL-BOWL LABOR',
          qty,
          stage: 'final',
          factor: '0.40',
        },
      )
    }

    if (toNumber(plan.garbage_disposals) > 0) {
      lines.push({
        code: 'LW50L80510',
        label: 'INSTALL GARBAGE DISPOSAL',
        qty: plan.garbage_disposals,
        stage: 'final',
        factor: '1.00',
      })
    }

    if (toNumber(plan.water_heater_tankless_qty) > 0) {
      lines.push({
        code: 'LW50L80530',
        label: 'INSTALL TANKLESS WATER HEATER',
        qty: plan.water_heater_tankless_qty,
        stage: 'final',
        factor: '1.00',
      })
    }

    if (toNumber(plan.kitchens) > 0) {
      lines.push({
        code: 'LW50L80550',
        label: 'INSTALL DISHWASHER',
        qty: numberString(Math.max(1, toNumber(plan.kitchens))),
        stage: 'final',
        factor: '1.00',
      })
    }

    return lines
  }, [effectiveWaterPoints, plan])

  function markDirty() {
    setHasPreviewed(false)
    setExistingTakeoffConflict(null)
  }

  function onPlanChange(event: ChangeEvent<HTMLInputElement>) {
    const { name, value } = event.target
    markDirty()
    setPlan((current) => ({ ...current, [name]: value }))
  }

  function onStandardItemChange(key: StandardItemKey, value: string) {
    markDirty()
    setItemOverrides((current) => ({ ...current, [key]: value }))
  }

  function addModel() {
    const next = modelsInput.trim()
    if (!next || models.includes(next)) return
    markDirty()
    setModels((current) => [...current, next])
    setModelsInput('')
  }

  function removeModel(model: string) {
    markDirty()
    setModels((current) => current.filter((entry) => entry !== model))
  }

  function previewReady() {
    setHasPreviewed(true)
    setExistingTakeoffConflict(null)
  }

  async function onSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setExistingTakeoffConflict(null)

    if (!hasPreviewed) {
      setHasPreviewed(true)
      return
    }

    if (!effectiveBaseline?.templateCode) {
      return
    }

    let resolvedProjectCode = selectedProjectCode

    try {
      if (projectMode === 'create') {
        const created = await createProject.mutateAsync({
          project_code: generateProjectCode(projectName),
          project_name: projectName.trim(),
          contractor_name: contractorName.trim() || undefined,
          foreman_name: foremanName.trim() || undefined,
        })
        resolvedProjectCode = created.project.project_code
      }

      await generateTakeoff.mutateAsync({
        project_code: resolvedProjectCode,
        template_code: effectiveBaseline.templateCode,
        tax_rate_override: null,
        plan: {
          stories: Number(plan.stories),
          kitchens: Number(plan.kitchens),
          garbage_disposals: Number(plan.garbage_disposals),
          laundry_rooms: Number(plan.laundry_rooms),
          lav_faucets: Number(plan.lav_faucets),
          toilets: Number(plan.toilets),
          showers: Number(plan.showers),
          bathtubs: Number(plan.bathtubs),
          half_baths: Number(plan.half_baths),
          double_bowl_vanities: Number(plan.double_bowl_vanities),
          hose_bibbs: Number(plan.hose_bibbs),
          ice_makers: Number(plan.ice_makers),
          water_heater_tank_qty: Number(plan.water_heater_tank_qty),
          water_heater_tankless_qty: Number(plan.water_heater_tankless_qty),
          sewer_distance_lf: plan.sewer_distance_lf,
          water_distance_lf: plan.water_distance_lf,
        },
      })
    } catch (error) {
      if (error instanceof ApiError && error.code === 'current_takeoff_exists') {
        const details = error.details as
          | { project_code: string; template_code: string; takeoff_id: string }
          | undefined
        if (details) {
          setExistingTakeoffConflict(details)
        }
      }
    }
  }

  const generateError =
    generateTakeoff.error instanceof ApiError &&
    generateTakeoff.error.code !== 'current_takeoff_exists'
      ? generateTakeoff.error.message
      : null

  const createError = createProject.error instanceof ApiError ? createProject.error.message : null

  const selectedTemplateCode = effectiveBaseline?.templateCode ?? null
  const selectedTemplateMissing =
    selectedTemplateCode !== null &&
    !(templates.data ?? []).some((template) => template.template_code === selectedTemplateCode)

  const conflictProjectName =
    activeProjects.find((project) => project.project_code === existingTakeoffConflict?.project_code)?.project_name ??
    (projectMode === 'create' ? projectName : 'selected project')

  return (
    <div className="space-y-6">
      <section className="flex flex-wrap items-end justify-between gap-4">
        <div>
          <div className="flex items-center gap-3">
            <Link
              className="rounded-full border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 transition hover:border-slate-400 hover:bg-slate-50"
              to="/projects"
            >
              Home
            </Link>
            <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-teal-700">
              Editor Flow
            </p>
          </div>
          <h2 className="mt-3 text-3xl font-semibold tracking-tight text-slate-900">
            Build and preview a new takeoff
          </h2>
          <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">
            Move through the business workflow from structure type to baseline, review the
            auto-generated operational lines, then accept the preview and generate the current
            takeoff.
          </p>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-600 shadow-sm">
          Signed in as <span className="font-medium text-slate-900">{session.data?.role}</span>
        </div>
      </section>

      <form className="space-y-6" onSubmit={onSubmit}>
        <InfoCard subtitle="Business-facing template selection" title="Step A · Structure Type">
          <div className="grid gap-4 lg:grid-cols-4">
            {STRUCTURE_OPTIONS.map((option) => (
              <button
                key={option.key}
                className={`rounded-3xl border px-5 py-5 text-left transition ${
                  structureType === option.key
                    ? 'border-teal-500 bg-teal-50'
                    : 'border-slate-200 bg-slate-50 hover:border-slate-300'
                }`}
                onClick={() => {
                  markDirty()
                  setStructureType(option.key)
                  setItemOverrides({})
                  if (option.key === 'Custom') {
                    setBaselineId('')
                  }
                }}
                type="button"
              >
                <p className="text-sm font-semibold text-slate-900">{option.label}</p>
                <p className="mt-2 text-sm leading-6 text-slate-500">{option.description}</p>
              </button>
            ))}
          </div>
        </InfoCard>

        {structureType !== 'Custom' ? (
          <InfoCard subtitle="Business-facing baseline variants" title="Step B · Baseline / Variant">
            <div className="grid gap-4 lg:grid-cols-2">
              {availableBaselines.map((option) => (
                <button
                  key={option.id}
                  className={`rounded-3xl border px-5 py-5 text-left transition ${
                    baselineId === option.id
                      ? 'border-teal-500 bg-teal-50'
                      : 'border-slate-200 bg-slate-50 hover:border-slate-300'
                  }`}
                  onClick={() => {
                    markDirty()
                    setBaselineId(option.id)
                    setItemOverrides({})
                  }}
                  type="button"
                >
                  <p className="text-sm font-semibold text-slate-900">{option.label}</p>
                  <p className="mt-2 text-sm leading-6 text-slate-500">{option.description}</p>
                </button>
              ))}
            </div>

            {selectedTemplateMissing ? (
              <div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-4 text-sm text-amber-800">
                The selected baseline is not available from the current official templates API.
              </div>
            ) : null}
          </InfoCard>
        ) : (
          <InfoCard subtitle="No baseline preloaded" title="Step B · Custom">
            <p className="text-sm leading-6 text-slate-600">
              Custom is now explicit in the workflow. The backend still requires a baseline
              template for final generation, so this path is currently preview-only.
            </p>
          </InfoCard>
        )}

        <InfoCard subtitle="Capture one or more models before leaving the page" title="Step C · Models">
          <div className="flex flex-wrap gap-3">
            <input
              className="min-w-[220px] flex-1 rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
              onChange={(event) => {
                markDirty()
                setModelsInput(event.target.value)
              }}
              onKeyDown={(event) => {
                if (event.key === 'Enter') {
                  event.preventDefault()
                  addModel()
                }
              }}
              placeholder="Add model number"
              type="text"
              value={modelsInput}
            />
            <button
              className="rounded-full border border-slate-300 px-4 py-2.5 text-sm font-medium text-slate-700 transition hover:border-slate-400 hover:bg-slate-50"
              onClick={addModel}
              type="button"
            >
              Add model
            </button>
          </div>

          {models.length ? (
            <div className="mt-4 flex flex-wrap gap-2">
              {models.map((model) => (
                <button
                  key={model}
                  className="rounded-full bg-slate-100 px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-200"
                  onClick={() => removeModel(model)}
                  type="button"
                >
                  {model} ×
                </button>
              ))}
            </div>
          ) : (
            <p className="mt-4 text-sm text-slate-500">
              Add model numbers when they help identify the baseline session. These are not yet
              persisted by the backend.
            </p>
          )}
        </InfoCard>

        <InfoCard subtitle="Choose one path only" title="Project">
          <div className="grid gap-4 lg:grid-cols-2">
            <button
              className={`rounded-3xl border px-5 py-5 text-left transition ${
                projectMode === 'existing'
                  ? 'border-teal-500 bg-teal-50'
                  : 'border-slate-200 bg-slate-50 hover:border-slate-300'
              }`}
              onClick={() => {
                markDirty()
                setProjectMode('existing')
              }}
              type="button"
            >
              <p className="text-sm font-semibold text-slate-900">Use existing project</p>
              <p className="mt-2 text-sm leading-6 text-slate-500">
                Select an open project and generate a new current takeoff from the chosen baseline.
              </p>
            </button>

            <button
              className={`rounded-3xl border px-5 py-5 text-left transition ${
                projectMode === 'create'
                  ? 'border-teal-500 bg-teal-50'
                  : 'border-slate-200 bg-slate-50 hover:border-slate-300'
              }`}
              onClick={() => {
                markDirty()
                setProjectMode('create')
              }}
              type="button"
            >
              <p className="text-sm font-semibold text-slate-900">Create new project</p>
              <p className="mt-2 text-sm leading-6 text-slate-500">
                Project code is now generated internally. Enter only the business-facing project
                details here.
              </p>
            </button>
          </div>

          {projectMode === 'existing' ? (
            <div className="mt-6">
              <label className="block">
                <span className="mb-2 block text-sm font-medium text-slate-700">Open project</span>
                <select
                  className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
                  onChange={(event) => {
                    markDirty()
                    setSelectedProjectCode(event.target.value)
                  }}
                  required
                  value={selectedProjectCode}
                >
                  <option value="">Select a project</option>
                  {activeProjects.map((project) => (
                    <option key={project.project_code} value={project.project_code}>
                      {project.project_name}
                      {project.contractor_name ? ` — ${project.contractor_name}` : ''}
                    </option>
                  ))}
                </select>
              </label>
            </div>
          ) : (
            <div className="mt-6 grid gap-4 lg:grid-cols-2">
              <label className="block">
                <span className="mb-2 block text-sm font-medium text-slate-700">Project name</span>
                <input
                  className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
                  onChange={(event) => {
                    markDirty()
                    setProjectName(event.target.value)
                  }}
                  required
                  type="text"
                  value={projectName}
                />
              </label>
              <label className="block">
                <span className="mb-2 block text-sm font-medium text-slate-700">
                  Contractor / builder
                </span>
                <input
                  className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
                  onChange={(event) => {
                    markDirty()
                    setContractorName(event.target.value)
                  }}
                  type="text"
                  value={contractorName}
                />
              </label>
              <label className="block lg:col-span-2">
                <span className="mb-2 block text-sm font-medium text-slate-700">Foreman</span>
                <input
                  className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
                  onChange={(event) => {
                    markDirty()
                    setForemanName(event.target.value)
                  }}
                  type="text"
                  value={foremanName}
                />
              </label>
            </div>
          )}
        </InfoCard>

        <div className="grid gap-6 xl:grid-cols-[1.05fr_0.95fr]">
          <div className="space-y-6">
            <InfoCard subtitle="Drivers that shape generated operational lines" title="Block A · Core / Generated Drivers">
              <div className="grid gap-4 md:grid-cols-2">
                <label className="block">
                  <span className="mb-2 block text-sm font-medium text-slate-700">Stories</span>
                  <select
                    className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
                    onChange={(event) => {
                      markDirty()
                      setPlan((current) => ({ ...current, stories: event.target.value }))
                    }}
                    value={plan.stories}
                  >
                    <option value="1">1 Story</option>
                    <option value="2">2 Stories</option>
                    <option value="3">3 Stories</option>
                    <option value="4">4 Stories</option>
                  </select>
                </label>

                <label className="block">
                  <span className="mb-2 block text-sm font-medium text-slate-700">
                    Water Points
                  </span>
                  <input
                    className="w-full rounded-2xl border border-slate-300 bg-slate-50 px-4 py-3 text-sm font-medium text-slate-900 outline-none"
                    readOnly
                    type="text"
                    value={numberString(derivedWaterPoints)}
                  />
                  <span className="mt-2 block text-xs text-slate-500">
                    Auto-calculated from current standard counts.
                  </span>
                </label>

                <label className="block">
                  <span className="mb-2 block text-sm font-medium text-slate-700">
                    Water Points Override
                  </span>
                  <input
                    className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
                    min="0"
                    onChange={(event) => {
                      markDirty()
                      setWaterPointsOverride(event.target.value)
                    }}
                    placeholder="Optional override, e.g. 18.5"
                    step="0.1"
                    type="number"
                    value={waterPointsOverride}
                  />
                  <span className="mt-2 block text-xs text-amber-700">
                    Visible and editable now. Final generation still uses backend-derived water
                    points until override support is added to the API.
                  </span>
                </label>

                <NumberField
                  label="Double Bowl"
                  name="double_bowl_vanities"
                  onChange={onPlanChange}
                  value={plan.double_bowl_vanities}
                />
                <NumberField
                  label="Sewer distance LF"
                  name="sewer_distance_lf"
                  onChange={onPlanChange}
                  step="0.01"
                  value={plan.sewer_distance_lf}
                />
                <NumberField
                  label="Water distance LF"
                  name="water_distance_lf"
                  onChange={onPlanChange}
                  step="0.01"
                  value={plan.water_distance_lf}
                />
              </div>
            </InfoCard>

            <InfoCard
              subtitle="Quantities drive the backend today. Baseline defaults are shown up front so selectors are not empty."
              title="Block B · Standard Fixture Counts + Item Selection"
            >
              {categoryItems.isError ? (
                <div className="mb-4 rounded-2xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">
                  {categoryItems.error instanceof Error
                    ? categoryItems.error.message
                    : 'Unable to load the live item catalog for category-backed selectors.'}
                </div>
              ) : null}

              <div className="mb-4 rounded-2xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm text-sky-800">
                Item selectors are now visible and preloaded by baseline. Backend item-level
                overrides are still pending, so these selections currently guide preview and review
                rather than final generation.
              </div>

              <div className="space-y-3">
                {STANDARD_ROWS.map((row) => (
                  (() => {
                    const apiItems = categoryItems.itemsByCategory[row.category] ?? []
                    const localDrafts = catalogDrafts[row.key]
                    const mergedOptions = [
                      ...apiItems.map((item) => ({
                        code: item.code,
                        label: item.description,
                      })),
                      ...localDrafts.filter(
                        (option) => !apiItems.some((item) => item.code === option.code),
                      ),
                    ]
                    const selectedValue =
                      mergedOptions.some((option) => option.code === itemSelections[row.key])
                        ? itemSelections[row.key]
                        : (mergedOptions[0]?.code ?? '')

                    return (
                      <div
                        key={row.key}
                        className="grid gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 lg:grid-cols-[1.3fr_0.6fr_1fr]"
                      >
                        <div>
                          <p className="text-sm font-semibold text-slate-900">{row.label}</p>
                          <p className="mt-1 text-xs leading-5 text-slate-500">
                            Category: {row.category}
                          </p>
                          {row.helpText ? (
                            <p className="mt-1 text-xs leading-5 text-slate-500">{row.helpText}</p>
                          ) : null}
                          {categoryItems.isLoading ? (
                            <p className="mt-2 text-xs text-slate-400">Loading live catalog items…</p>
                          ) : null}
                          {!categoryItems.isLoading && mergedOptions.length === 0 ? (
                            <p className="mt-2 text-xs text-amber-700">
                              No active items found for this category yet.
                            </p>
                          ) : null}
                        </div>

                        <label className="block">
                          <span className="mb-2 block text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                            Quantity
                          </span>
                          <input
                            className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
                            min="0"
                            name={row.quantityKey}
                            onChange={onPlanChange}
                            step="1"
                            type="number"
                            value={plan[row.quantityKey]}
                          />
                        </label>

                        <label className="block">
                          <span className="mb-2 block text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                            Selected item
                          </span>
                          <select
                            className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
                            disabled={mergedOptions.length === 0}
                            onChange={(event) => onStandardItemChange(row.key, event.target.value)}
                            value={selectedValue}
                          >
                            {mergedOptions.length === 0 ? (
                              <option value="">No active items</option>
                            ) : (
                              mergedOptions.map((option) => (
                                <option key={option.code} value={option.code}>
                                  {option.code} — {option.label}
                                </option>
                              ))
                            )}
                          </select>
                        </label>
                      </div>
                    )
                  })()
                ))}
              </div>
            </InfoCard>
          </div>

          <div className="space-y-6">
            <InfoCard
              subtitle="Visible operational lines generated from the current inputs"
              title="Block C · Auto-generated Operational Lines"
            >
              <div className="mb-4 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
                These lines are now visible before generation. Pre-generate editing of these
                operational lines still needs broader backend support, so this block is currently
                preview-focused.
              </div>

              <div className="overflow-x-auto">
                <table className="min-w-full border-separate border-spacing-y-2">
                  <thead>
                    <tr className="text-left text-[11px] uppercase tracking-[0.18em] text-slate-400">
                      <th className="px-3 py-2">Item</th>
                      <th className="px-3 py-2">Line</th>
                      <th className="px-3 py-2">Qty</th>
                      <th className="px-3 py-2">Stage</th>
                      <th className="px-3 py-2">Factor</th>
                    </tr>
                  </thead>
                  <tbody>
                    {autoGeneratedLines.map((line) => (
                      <tr key={`${line.stage}-${line.code}`} className="rounded-2xl bg-slate-50 text-sm text-slate-700">
                        <td className="rounded-l-2xl px-3 py-3 font-semibold text-slate-900">
                          {line.code}
                        </td>
                        <td className="px-3 py-3">{line.label}</td>
                        <td className="px-3 py-3">{line.qty}</td>
                        <td className="px-3 py-3 capitalize">{line.stage}</td>
                        <td className="rounded-r-2xl px-3 py-3">{line.factor}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </InfoCard>

            <InfoCard
              subtitle="Optional extras stay separate from the standard baseline flow"
              title="Block D · Optional / Premium / Extra Items"
            >
              <div className="rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
                Premium items, item-category filtering, and item creation are shown here in a
                lightweight review flow. Persisting them into final generation still needs backend
                item/catalog endpoints.
              </div>

              <div className="mt-4 flex flex-wrap gap-3">
                <button
                  className="rounded-full border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 transition hover:border-slate-400 hover:bg-slate-50"
                  onClick={() => {
                    markDirty()
                    setShowExtras((current) => !current)
                  }}
                  type="button"
                >
                  {showExtras ? 'Hide extras' : 'Show extras'}
                </button>
                <button
                  className="rounded-full border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 transition hover:border-slate-400 hover:bg-slate-50"
                  onClick={() => setShowCreateItemModal(true)}
                  type="button"
                >
                  Create item
                </button>
              </div>

              {showExtras ? (
                <div className="mt-5 space-y-3">
                  {extraItems.map((item) => (
                    <div
                      key={item.id}
                      className="grid gap-3 rounded-2xl border border-slate-200 bg-slate-50 p-4 md:grid-cols-[1.2fr_0.8fr_auto]"
                    >
                      <label className="block">
                        <span className="mb-2 block text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                          Item
                        </span>
                        <input
                          className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
                          onChange={(event) => {
                            markDirty()
                            setExtraItems((current) =>
                              current.map((entry) =>
                                entry.id === item.id
                                  ? { ...entry, item_label: event.target.value }
                                  : entry,
                              ),
                            )
                          }}
                          type="text"
                          value={item.item_label}
                        />
                      </label>
                      <label className="block">
                        <span className="mb-2 block text-xs font-semibold uppercase tracking-[0.16em] text-slate-500">
                          Stage
                        </span>
                        <select
                          className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
                          onChange={(event) => {
                            markDirty()
                            setExtraItems((current) =>
                              current.map((entry) =>
                                entry.id === item.id
                                  ? {
                                      ...entry,
                                      stage: event.target.value as ExtraItemDraft['stage'],
                                    }
                                  : entry,
                              ),
                            )
                          }}
                          value={item.stage}
                        >
                          <option value="ground">Ground</option>
                          <option value="topout">TopOut</option>
                          <option value="final">Final</option>
                        </select>
                      </label>
                      <div className="flex items-end">
                        <button
                          className="rounded-full border border-rose-200 px-4 py-2 text-sm font-medium text-rose-700 transition hover:bg-rose-50"
                          onClick={() => {
                            markDirty()
                            setExtraItems((current) => current.filter((entry) => entry.id !== item.id))
                          }}
                          type="button"
                        >
                          Remove
                        </button>
                      </div>
                    </div>
                  ))}

                  <button
                    className="rounded-full border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 transition hover:border-slate-400 hover:bg-slate-50"
                    onClick={() => {
                      markDirty()
                      setExtraItems((current) => [
                        ...current,
                        {
                          id: crypto.randomUUID(),
                          item_label: '',
                          stage: 'final',
                        },
                      ])
                    }}
                    type="button"
                  >
                    Add extra item row
                  </button>
                </div>
              ) : null}
            </InfoCard>
          </div>
        </div>

        {createError ? (
          <InfoCard subtitle="Project creation failed" title="Unable to create project">
            <p className="text-sm text-rose-700">{createError}</p>
          </InfoCard>
        ) : null}

        {generateError ? (
          <InfoCard subtitle="Takeoff generation failed" title="Unable to generate">
            <p className="text-sm text-rose-700">{generateError}</p>
          </InfoCard>
        ) : null}

        {existingTakeoffConflict ? (
          <InfoCard subtitle="The backend rejected duplicate CURRENT generation" title="Current takeoff already exists">
            <p className="text-sm leading-6 text-slate-600">
              A current takeoff already exists for{' '}
              <span className="font-medium text-slate-900">{conflictProjectName}</span> on the{' '}
              <span className="font-medium text-slate-900">
                {effectiveBaseline?.label ?? existingTakeoffConflict.template_code}
              </span>{' '}
              baseline.
            </p>
            <div className="mt-4 flex flex-wrap gap-3">
              <Link
                className="rounded-full bg-slate-950 px-4 py-2 text-sm font-medium text-white transition hover:bg-slate-800"
                to={`/takeoffs/${existingTakeoffConflict.takeoff_id}`}
              >
                Open existing current takeoff
              </Link>
              <button
                className="rounded-full border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 transition hover:border-slate-400 hover:bg-slate-50"
                onClick={() => setExistingTakeoffConflict(null)}
                type="button"
              >
                Dismiss
              </button>
            </div>
          </InfoCard>
        ) : null}

        <InfoCard subtitle="Review the session before generating" title="Preview">
          <div className="grid gap-4 lg:grid-cols-2">
            <div className="rounded-2xl bg-slate-50 px-4 py-4">
              <p className="text-[11px] uppercase tracking-[0.18em] text-slate-400">Structure</p>
              <p className="mt-1 text-sm font-semibold text-slate-900">{structureType}</p>
            </div>
            <div className="rounded-2xl bg-slate-50 px-4 py-4">
              <p className="text-[11px] uppercase tracking-[0.18em] text-slate-400">Baseline</p>
              <p className="mt-1 text-sm font-semibold text-slate-900">
                {effectiveBaseline?.label ?? 'Custom'}
              </p>
            </div>
            <div className="rounded-2xl bg-slate-50 px-4 py-4">
              <p className="text-[11px] uppercase tracking-[0.18em] text-slate-400">Project path</p>
              <p className="mt-1 text-sm font-semibold text-slate-900">
                {projectMode === 'existing'
                  ? selectedProject?.project_name || 'Select a project'
                  : projectName || 'Enter a project name'}
              </p>
            </div>
            <div className="rounded-2xl bg-slate-50 px-4 py-4">
              <p className="text-[11px] uppercase tracking-[0.18em] text-slate-400">Models</p>
              <p className="mt-1 text-sm font-semibold text-slate-900">
                {models.length ? models.join(', ') : 'No models added'}
              </p>
            </div>
            <div className="rounded-2xl bg-slate-50 px-4 py-4">
              <p className="text-[11px] uppercase tracking-[0.18em] text-slate-400">Water points</p>
              <p className="mt-1 text-sm font-semibold text-slate-900">
                {numberString(effectiveWaterPoints)}
              </p>
            </div>
            <div className="rounded-2xl bg-slate-50 px-4 py-4">
              <p className="text-[11px] uppercase tracking-[0.18em] text-slate-400">Auto lines</p>
              <p className="mt-1 text-sm font-semibold text-slate-900">
                {autoGeneratedLines.length} visible operational lines
              </p>
            </div>
          </div>

          {!hasPreviewed ? (
            <div className="mt-5 rounded-2xl border border-sky-200 bg-sky-50 px-4 py-3 text-sm text-sky-800">
              Preview this session before final generation to review the selected baseline and
              generated operational lines.
            </div>
          ) : null}

          {structureType === 'Custom' ? (
            <div className="mt-5 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
              Custom is visible and explicit now, but final generation still requires a baseline
              template in the current backend/API.
            </div>
          ) : null}
        </InfoCard>

        <div className="flex flex-wrap justify-end gap-3">
          <Link
            className="rounded-full border border-slate-300 px-5 py-3 text-sm font-medium text-slate-700 transition hover:border-slate-400 hover:bg-slate-50"
            to="/projects"
          >
            Cancel
          </Link>
          <button
            className="rounded-full border border-slate-300 px-5 py-3 text-sm font-medium text-slate-700 transition hover:border-slate-400 hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-60"
            disabled={isBusy}
            onClick={previewReady}
            type="button"
          >
            Preview
          </button>
          <button
            className="rounded-full bg-slate-950 px-5 py-3 text-sm font-semibold text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60"
            disabled={
              isBusy ||
              !hasPreviewed ||
              structureType === 'Custom' ||
              (projectMode === 'existing' && !selectedProjectCode) ||
              (projectMode === 'create' && projectName.trim() === '') ||
              !effectiveBaseline?.templateCode
            }
            type="submit"
          >
            {isBusy ? 'Working...' : 'Generate / Accept Takeoff'}
          </button>
        </div>
      </form>

      {showCreateItemModal ? (
        <div className="fixed inset-0 z-40 flex items-center justify-center bg-slate-950/45 px-6 py-10">
          <div className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl">
            <div className="flex items-start justify-between gap-4">
              <div>
                <p className="text-[11px] font-semibold uppercase tracking-[0.24em] text-teal-700">
                  Create Item
                </p>
                <h3 className="mt-2 text-2xl font-semibold tracking-tight text-slate-900">
                  Local premium item draft
                </h3>
                <p className="mt-2 text-sm text-slate-500">
                  This modal supports the approved page flow now, but saving the item into the real
                  catalog still needs item API support.
                </p>
              </div>
              <button
                className="rounded-full border border-slate-300 px-3 py-1.5 text-sm font-medium text-slate-600 transition hover:border-slate-400 hover:bg-slate-50"
                onClick={() => setShowCreateItemModal(false)}
                type="button"
              >
                Close
              </button>
            </div>

            <div className="mt-6 grid gap-4">
              <label className="block">
                <span className="mb-2 block text-sm font-medium text-slate-700">Item label</span>
                <input
                  className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
                  onChange={(event) =>
                    setDraftItemModal((current) => ({ ...current, label: event.target.value }))
                  }
                  type="text"
                  value={draftItemModal.label}
                />
              </label>

              <label className="block">
                <span className="mb-2 block text-sm font-medium text-slate-700">Item code</span>
                <input
                  className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
                  onChange={(event) =>
                    setDraftItemModal((current) => ({ ...current, code: event.target.value }))
                  }
                  type="text"
                  value={draftItemModal.code}
                />
              </label>

              <label className="block">
                <span className="mb-2 block text-sm font-medium text-slate-700">Category</span>
                <select
                  className="w-full rounded-2xl border border-slate-300 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-teal-500 focus:ring-4 focus:ring-teal-100"
                  onChange={(event) =>
                    setDraftItemModal((current) => ({
                      ...current,
                      category: event.target.value as DraftItemModal['category'],
                    }))
                  }
                  value={draftItemModal.category}
                >
                  <option value="">Select a category</option>
                  {Object.entries(STANDARD_ITEM_OPTIONS).map(([key, options]) => (
                    <option key={key} value={key}>
                      {options[0].label}
                    </option>
                  ))}
                </select>
              </label>
            </div>

            <div className="mt-6 flex items-center justify-end gap-3">
              <button
                className="rounded-full border border-slate-300 px-4 py-2.5 text-sm font-medium text-slate-700 transition hover:border-slate-400 hover:bg-slate-50"
                onClick={() => setShowCreateItemModal(false)}
                type="button"
              >
                Cancel
              </button>
              <button
                className="rounded-full bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:bg-slate-400"
                disabled={
                  draftItemModal.label.trim() === '' ||
                  draftItemModal.code.trim() === '' ||
                  draftItemModal.category === ''
                }
                onClick={() => {
                  const category = draftItemModal.category
                  if (!category) return
                  markDirty()
                  setCatalogDrafts((current) => ({
                    ...current,
                    [category]: [
                      ...current[category],
                      {
                        code: draftItemModal.code.trim(),
                        label: draftItemModal.label.trim(),
                      },
                    ],
                  }))
                  setItemOverrides((current) => ({
                    ...current,
                    [category]: draftItemModal.code.trim(),
                  }))
                  setDraftItemModal({ label: '', code: '', category: '' })
                  setShowCreateItemModal(false)
                }}
                type="button"
              >
                Add local item
              </button>
            </div>
          </div>
        </div>
      ) : null}
    </div>
  )
}
