from __future__ import annotations

from typing import Protocol

from app.domain.item import Item


class ItemRepository(Protocol):
    def upsert(self, item: Item) -> None: ...
    def get(self, code: str) -> Item: ...
    def list(self, *, include_inactive: bool = False) -> tuple[Item, ...]: ...
    def delete(self, code: str) -> None: ...
