from __future__ import annotations

from typing import Protocol
from decimal import Decimal

from app.domain.project import Project


class ProjectRepository(Protocol):
    def upsert(self, project: Project) -> None: ...
    def get(self, code: str) -> Project: ...
    def list(self, *, include_inactive: bool = False) -> tuple[Project, ...]: ...
    def set_valve_discount(self, code: str, *, valve_discount: Decimal) -> None: ...
    def delete(self, code: str) -> None: ...
