from __future__ import annotations

from typing import Protocol

from app.domain.template import Template


class TemplateRepository(Protocol):
    def upsert(self, template: Template) -> None: ...
    def get(self, code: str) -> Template: ...
    def list(self, *, include_inactive: bool = False) -> tuple[Template, ...]: ...
    def delete(self, code: str) -> None: ...
